# Generated by Django 5.0 on 2024-01-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='posts',
            field=models.ManyToManyField(to='coffee.tag'),
        ),
    ]
