# Generated by Django 5.0 on 2024-01-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_rename_post_comment_post_id_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
